name: Maintenance/Chore
description: Request a maintenance task or chore.
title: "[Chore]: "
labels: ["chore", "maintenance"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest a maintenance task or housekeeping improvement.

  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: Describe the maintenance task or chore you'd like to suggest.
      placeholder: "e.g., Update the Discord.js dependency to the latest version."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why is this needed?
      description: Explain why this task is important or how it will help the project.
      placeholder: "e.g., Staying up to date ensures compatibility with future updates."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other details, links, or references.
      placeholder: "e.g., Related issues, PRs, or documentation links."
    validations:
      required: false
