name: Documentation Request
description: Request improvements or additions to the project's documentation.
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation by telling us what's missing or unclear!

  - type: textarea
    id: docs-section
    attributes:
      label: What section of the documentation needs improvement?
      description: Specify the section or area where you encountered issues or think more clarity is needed.
      placeholder: "e.g., Setup Instructions"
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Changes
      description: Describe what you'd like to add or change in the documentation.
      placeholder: "e.g., Include a troubleshooting section for common installation issues."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any additional details, screenshots, or links that might help.
      placeholder: "e.g., A link to a related issue or relevant logs."
    validations:
      required: false
