name: Question/Support Request
description: Ask a question or request help with using the project.
title: "[Question]: "
labels: ["question", "support"]
body:
  - type: markdown
    attributes:
      value: |
        Got a question or need help? Fill out the form below, and we'll do our best to assist you!

  - type: textarea
    id: question
    attributes:
      label: What is your question or issue?
      description: Describe your question or what you need help with in as much detail as possible.
      placeholder: "e.g., How do I set up the bot locally?"
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What have you tried so far?
      description: Let us know what you've tried or where you're stuck.
      placeholder: "e.g., I followed the setup guide, but I got an error during the installation."
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if follow-up is needed?
      placeholder: "e.g., email, @discord, etc."
    validations:
      required: false
