name: Security Vulnerability
description: Report a potential security vulnerability.
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this template to report potential security vulnerabilities. To keep this information private, you can email us at [security@example.com].

  - type: textarea
    id: description
    attributes:
      label: Description of the Vulnerability
      description: Provide as much detail as possible about the vulnerability.
      placeholder: "e.g., SQL injection vulnerability in the login route."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List detailed steps to reproduce the issue, if applicable.
      placeholder: |
        1. Go to...
        2. Perform action...
        3. Observe the vulnerability...
    validations:
      required: true

  - type: textarea
    id: potential-impact
    attributes:
      label: Potential Impact
      description: Describe the potential risk or harm this vulnerability could cause.
      placeholder: "e.g., This could allow unauthorized access to user data."
    validations:
      required: true

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: Mitigation Suggestions
      description: If you have ideas for resolving the issue, please provide them here.
      placeholder: "e.g., Sanitize inputs and use parameterized queries."
    validations:
      required: false
